export const affiliateLinks = {
  cloudcone: "https://vps-recommend.github.io/go/cloudcone/",
  racknerd: "https://vps-recommend.github.io/go/racknerd/",
  bandwagonhost: "https://vps-recommend.github.io/go/bandwagonhost/",
  vultr: "https://vps-recommend.github.io/go/vultr/",
  hostdare: "https://vps-recommend.github.io/go/hostdare/",
  linode: "https://vps-recommend.github.io/go/linode/",
  digitalocean: "https://vps-recommend.github.io/go/digitalocean/",
  cloudways: "https://vps-recommend.github.io/go/cloudways/",
  dmit: "https://vps-recommend.github.io/go/dmit/",
  aliyun: "https://vps-recommend.github.io/go/aliyun/",
  evoxt: "https://vps-recommend.github.io/go/evoxt/",
  hostwinds: "https://vps-recommend.github.io/go/hostwinds/",
  kamatera: "https://vps-recommend.github.io/go/kamatera/",
  lisahost: "https://vps-recommend.github.io/go/lisahost/",
};
